# The client-deployment.yaml file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # Set the number of replicas to 3 for better availability and load balancing.
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        # The image path to your Google Container Registry (GCR) path.
        image: us-central1-docker.pkg.dev/iron-handler-471307-u7/gcp-practice-images/client:latest
        ports:
        - containerPort: 3000
        env:
        # Note: Your frontend code (running in the browser) cannot use "http://server-service"
        # because that's an internal-only name. You must get the public IP of the
        # server-service once it's provisioned and update your frontend's code to use that IP.
        - name: REACT_APP_YOUR_HOSTNAME
          value: "http://server-service"
