# The client-deployment.yaml file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # Set the number of replicas to 3 for better availability and load balancing.
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        # The image path to your Google Container Registry (GCR) path.
        image: us-central1-docker.pkg.dev/iron-handler-471307-u7/gcp-practice-images/client:latest
        ports:
        - containerPort: 3000
        env:
        # Now that the server-service has a public IP, we can use it to
        # configure the frontend's backend API URL.
        - name: REACT_APP_YOUR_HOSTNAME
          value: "http://34.28.153.155:5000"
