# The server-deployment.yaml file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  # Set the number of replicas to 3 for better availability and load balancing.
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        # The image path to your Google Container Registry (GCR) path.
        image: us-central1-docker.pkg.dev/iron-handler-471307-u7/gcp-practice-images/server:latest
        ports:
        - containerPort: 5000
        env:
        # We need to retrieve the ATLAS_URI from a secret in Kubernetes.
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: secrets
              key: ATLAS_URI
